var arr=["Inception",
"Predestination",
"Argo",
"Rush",
"Her",
"The Dark Knight",
"Batman Begins",
"Catch Me If You Can",
"Shutter Island",
"The Departed",
"The Dark Knight Rises",
"Edge of Tomorrow",
"The Imitation Game",
"Sherlock Holmes",
"Dunkirk",
"Interstellar",
"The Prestige",
"Avengers",
"Avengers:Age of Ultron",
"Pulp Fiction",
"The Midnight Meat Train",
"Limitless",
"12 Years a Slave",
"Forrest Gump",
"The Shawshank Redemption",
"The Godfather",
"The Godfather Part II",
"Pirates of the Carribean ",
"Harry Potter ",
"Marvel ",
"Fantastic Beasts and Where to Find Them",
"Dark Shadows ",
"Goodfellas",
"Star Wars ",
"Black Mass",
"Transcendence",
"The Matrix",
"The Revenant",
"Fight Club",
"Oblivion",
"Schindler's List",
"Saving Private Ryan",
"Gladiator",
"12 Monkeys",
"Indiana Jones and the Raiders of the Lost Ark",
"Dumb and Dumber",
"The Hangover",
"The Lord of the Rings: The Fellowship of the Ring",
"The Lord of the Rings: The Two Towers",
"The Lord of the Rings: The Return of the King",
"The Lion King",
"Hero",
"Big Hero 6",
"How toTrain Your Dragon",
"Finding Nemo",
"Titanic",
"The Iron Giant",
"Toy Story 1",
"Toy Story 2",
"Toy Story 3",
"The Incredibles",
"Monsters,Inc.",
"Ratatouille",
"Wall-E",
"Frozen",
"Inside Out",
"Despicable Me",
"Shrek",
"Back to the Future",
"The Silence of the Lambs",
"One Flew Over the Cuckoo's Nest",
"12 Angry Men",
"Seven Samurai",
"Léon: The Professional",
"Se7en",
"Sweeney Todd: The Demon Barber of Fleet Street",
"City Lights",
"The Green Mile",
"Apocalypse Now",
"American History X",
"Thw Pianist",
"Casablanca",
"The Great Dictator",
"Modern Times",
"Django Unchained",
"The Shining",
"Braveheart",
"Halloween",
"Get Out",
"Dead Silence",
"The Conjuring",
"IT",
"Psycho",
"The Babadook",
"The Exorcist",
"Scream",
"A Nightmare on Elm Street",
"Once Upon a Time in America",
"The Anchorman",
"21 Jump Street",
"22 Jump Street",
"Zoolander",
"Neighbors",
"Ted",
"Inglourious Basterds",
"Taxi Driver",
"A Clockwork Orange",
"Good Will Hunting",
"Scarface",
"To Kill a Mockingbird",
"The Hunt",
"Hacksaw Ridge",
"The Wolf of Wall Street",
"Room",
"A Beautiful Mind",
"Heat",
"Warrior",
"V for Vendetta",
"Unforgiven",
"The Good, the Bad and the Ugly",
"Chinatown",
"Vertigo",
"Rear Window",
"Raging Bull",
"Escape Plan",
"Rambo",
"Gone Girl",
"Jack Reacher",
"Vanilla Sky",
"Fury",
"Troy",
"World War Z",
"The Curious Case of Benjamin Button",
"Moneyball",
"Blood Diamond",
"The Aviator",
"Gangs of New York",
"J.Edgar",
"Orphan",
"Edward Scissorhands"]
module.exports=arr